FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY inference_pb2.py inference_pb2_grpc.py /app/
COPY worker.py model_loader.py batching.py /app/
COPY proto/ /app/proto/

CMD ["python", "worker.py"]
