# Переопределяется при необходимости
gateway:
  image:
    repository: grpc-gateway
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50051

worker:
  image:
    repository: grpc-worker
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1

redis:
  image: redis:7-alpine
  service:
    port: 6379
