apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grpc-inference.fullname" . }}
  labels:
    app: {{ include "grpc-inference.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "grpc-inference.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "grpc-inference.name" . }}
    spec:
      containers:
      - name: server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 50051
          name: grpc
        # Опционально: ресурсы
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"