apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grpc-inference.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ include "grpc-inference.name" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "grpc-inference.name" . }}-worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
