
# в редми написал, но на всякий и тут продублирую, написал, задание требует 
image: python:3.11-slim

stages:
  - test
  - reproducible

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python ml_pipeline.py

reproducible:
  stage: reproducible
  script:
    - python ml_pipeline.py
  artifacts:
    paths:
      - model.joblib
      - requirements.txt
      - ml_pipeline.py
    expire_in: 1 week
