upstream ml_backend {
    server ml-green:8000;
    server ml-blue:8000 backup;
}

server {
    listen 80;

    location / {
        proxy_pass http://ml_backend;
        proxy_set_header Host $host;
        proxy_next_upstream error timeout http_500 http_502 http_503;
    }
}
